// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJWXAnskXhC2-0aVbdk6kSZ8y7zh2Q0ns',
    appId: '1:136391405566:web:3277db47e3dc4670619aaf',
    messagingSenderId: '136391405566',
    projectId: 'lavajato-5944c',
    authDomain: 'lavajato-5944c.firebaseapp.com',
    storageBucket: 'lavajato-5944c.firebasestorage.app',
    measurementId: 'G-ZHZ019XBV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo_CMOjQRbf_-bEGjMWVd4ADtQ1f8OwOg',
    appId: '1:136391405566:android:2665b2b7600f8708619aaf',
    messagingSenderId: '136391405566',
    projectId: 'lavajato-5944c',
    storageBucket: 'lavajato-5944c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw9P8mvbO5pdWlQmxQVbyRydDYzSHDIE0',
    appId: '1:136391405566:ios:c373b2d560c49d0c619aaf',
    messagingSenderId: '136391405566',
    projectId: 'lavajato-5944c',
    storageBucket: 'lavajato-5944c.firebasestorage.app',
    iosBundleId: 'br.dev.victorleao.lavajato',
  );
}
