import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:lavajato/blocs/vehicle/vehicle_bloc.dart';
import 'package:lavajato/domain/entities/car_entity.dart';

class AddVehicleForm extends StatefulWidget {
  const AddVehicleForm({super.key});

  @override
  State<AddVehicleForm> createState() => _AddVehicleFormState();
}

class _AddVehicleFormState extends State<AddVehicleForm> {
  final _formKey = GlobalKey<FormState>();
  final _makeController = TextEditingController();
  final _modelController = TextEditingController();
  final _licensePlateController = TextEditingController();

  @override
  void dispose() {
    _makeController.dispose();
    _modelController.dispose();
    _licensePlateController.dispose();
    super.dispose();
  }

  void _submit() {
    if (_formKey.currentState!.validate()) {
      final car = CarEntity(
        id: '', // ID will be generated by Firestore
        make: _makeController.text,
        model: _modelController.text,
        licensePlate: _licensePlateController.text,
      );
      context.read<VehicleBloc>().add(AddVehicle(car));
      Navigator.of(context).pop();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Form(
      key: _formKey,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          TextFormField(
            controller: _makeController,
            decoration: const InputDecoration(labelText: 'Marca'),
            validator: (value) {
              if (value == null || value.isEmpty) {
                return 'Por favor, insira a marca do veículo';
              }
              return null;
            },
          ),
          TextFormField(
            controller: _modelController,
            decoration: const InputDecoration(labelText: 'Modelo'),
            validator: (value) {
              if (value == null || value.isEmpty) {
                return 'Por favor, insira o modelo do veículo';
              }
              return null;
            },
          ),
          TextFormField(
            controller: _licensePlateController,
            decoration: const InputDecoration(labelText: 'Placa'),
            validator: (value) {
              if (value == null || value.isEmpty) {
                return 'Por favor, insira a placa do veículo';
              }
              return null;
            },
          ),
          const SizedBox(height: 16),
          ElevatedButton(
            onPressed: _submit,
            child: const Text('Adicionar Veículo'),
          ),
        ],
      ),
    );
  }
}
